CC		:= cc
INCLUDES	:= 
#-I/opt/homebrew/Cellar/json-c/0.18/include/json-c \
#-I/opt/homebrew/opt/ncurses/include \
#-I/opt/homebrew/include 
CFLAGS 	:= -O3 -flto $(INCLUDES) -D_POSIX_C_SOURCE=200809L
LDFLAGS := $(CFLAGS) \
#-L/opt/homebrew/Cellar/json-c/0.18/lib \
#-L/opt/homebrew/opt/ncurses/lib \
#-L/opt/homebrew/lib \
#-Wl,-rpath,/opt/homebrew/lib \
-lcurl -lpthread -lm
TARGET  := myapp
SRCS    := $(wildcard src/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
