CC		:= cc
CFLAGS 	:= -g -Wall
LDFLAGS := $(CFLAGS) \
-lcurl -lpthread -lm
TARGET  := myapp
SRCS    := $(wildcard src2/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
