CC		:= cc
INCLUDES	:= 
CFLAGS 	:= -O3 -flto $(INCLUDES) -D_POSIX_C_SOURCE=200809L
LDFLAGS := $(CFLAGS) \
-lm -lcurl -lpthread
TARGET  := myapp
SRCS    := $(wildcard src/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
